
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
      ##  mapper-locations: classpath:/mapper/*Mapper.xml
      ##  #  mapper.xml映射文件
    ##  type-aliases-package: com.xuan.demo.entity
    ###  实体类名
spring:
  thymeleaf:
    cache: false
  #    关闭缓存
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xuan?useUnicode=true&characterEncoding=UTF-8
    username: localuser
    password: 123456
    hikari:
      #      连接池
      pool-name: DateHikariCP
      #      连接池别名
      minimum-idle: 5
      #      min空闲连接
      idle-timeout: 6000000
      #      空闲连接存活时长
      maximum-pool-size: 10
      #      最大连接数
      auto-commit: true
      #      连接池返回的连接自动提交
      max-lifetime: 600000
      #      连接最大存活时间
      connection-test-query: Select 1
      #      测试连接可用语句
      connection-timeout: 30000
#      连接超时时间

#logging:
#  #  mybatisSQL打印（方法接口所在的包）
#  level:
#    com.xuan.demo.mapper: debug
